### ISSUE TITLE
Please add a LICENSE to this repository.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/fhwr-unflattener#1]
Hi, I noticed that this repository is public but has no clear license declarations anywhere. Please add some sort of LICENSE declaration so that we can continue making this code public.

Generally, we default to MPL2 for code repos; you can grab a copy from https://www.mozilla.org/media/MPL/2.0/index.815ca599c9df.txt unless another license is necessary due to third-party requirements or other circumstances.

**Comment by openjck** [comment]
Neat! I'll do this right now.

Do you mind telling me how you identified this problem? I was thinking of writing a bot someday that opened issues about missing licenses. Was this opened by a bot?

**Comment by openjck** [comment]
Done with f167a40bac8abce30fafc293262e269a6c1a355e

**Comment by openjck** [comment]
Can do.

Also, just a friendly FYI that you may be missing some repos. I normally start repos out under my personal account and then transfer them to the *mozilla* organization, and I haven't been pinged about missing LICENSEs in those situations.

**Comment by floatingatoll** [comment]
Yeah, I do my best as a human being, but as you've obviously worked out, a
bot could be *so much better* here. Every six months I email GitHub Support
and ask them to prohibit users from forking or transferring repos into our
org unless they're licensed. No word to date. Maybe someday.

**Comment by openjck** [comment]
I appreciate it. You're doing a good job. I would have forgotten about the LICENSE without you. :smile:
